 <?php print $scripts ?>
  <?php print $closure ?>
  <!-- Start of StatCounter Code for Drupal -->
<script type="text/javascript">
var sc_project=4227893;
var sc_invisible=1;
var sc_security="3748d6f4";
</script>
<script type="text/javascript"
src="http://www.statcounter.com/counter/counter.js"></script>
<noscript><div class="statcounter"><a title="drupal
statistics module" href="http://statcounter.com/drupal/"
target="_blank"><img class="statcounter"
src="http://c.statcounter.com/4227893/0/3748d6f4/1/"
alt="drupal statistics module"></a></div></noscript>
<!-- End of StatCounter Code for Drupal -->
  </body>
</html>
