<?php
/**
 * @file
 * Code for the Company feature.
 */

include_once 'mc_company.features.inc';

function mc_company_late_form_alter(&$form, &$form_state, $form_id){
    global $user;

    if(!is_ct_form($form,"company")){
        return; //exit if not company node.
    }

    //remove some fields from non admin users
    if($user->uid > 1){
        $form['#after_build'][] = 'mc_company_node_form_after_build';
        unset($form['og_selective']);
        unset($form['og_register']);
        unset($form['og_directory']);
        unset($form['og_menu']);
        unset($form['og_private']);
    }

}

function mc_company_node_form_after_build($form, &$form_state){

    $form['body_field']['format']['#access'] = false;
    //modify some files default values
    $form['field_industry']['value']['#options'][''] = "Choose...";
    $form['field_company_size']['value']['#options'][''] = "Choose...";

    unset($form['field_ishiring']['value']['']);
    unset($form['field_islookingfund']['value']['']);

    return $form;
}

function mc_company_preprocess($vars,$hook){
    if($hook == 'block'){
        $cblock = $vars['block'];
        if($cblock->module == 'ds' && $cblock->bid == 'ds-f75e0974f5723f830348fb4d9444931b'){
            $cblock->subject = t("Where it's at");
        }
        if($cblock->module == 'ds' && $cblock->bid == 'ds-3cc955558f2299879e4f9d02f84134bd'){
            $cblock->subject = t("More Info");
        }
    }
}

function mc_company_views_query_alter(&$view, &$query) {

    if($view->name != 'latest_pages'){
        return ;
    }

    if($view->current_display != 'page_8'){
        return;
    }

    $section = arg(1);
    $arg = arg(2);
    $filter = false;

    switch($section){
        case 'industry':
            if($arg > 0){
                $tid = arg(2);
                $query->add_table('term_node');
                $query->add_where('term','term_node.tid = %d',$arg);
                $filter = true;
            }
        break;
        case 'size':
            if(!empty($arg)){
                $query->add_table('content_type_company');
                $query->add_where(NULL,"field_company_size_value = '%s'",$arg);
                $filter = true;
            }
        break;
        case 'tag':
            switch($arg){
                case 'hiring':
                    $query->add_table('content_type_company');
                    $query->add_where(NULL,"field_ishiring_value = %d",1);
                    $filter = true;
                break;
                case 'funding':
                    $query->add_table('content_type_company');
                    $query->add_where(NULL,"field_islookingfund_value = %d",1);
                    $filter = true;
                break;
            }
        break;
        default;
    }

    if($section && !$filter){
        drupal_goto("directory");
    }
}