<?php

function mt_preprocess($vars,$hook){
    if($hook == 'block'){
        $cblock = $vars['block'];
        if($cblock->module == 'ds' && $cblock->bid == 'ds-0b596e3199de270de74a2f6e8f0d1525'){
            $cblock->subject = t("Where it's at"); 
        }
	if($cblock->module == 'views' && $cblock->delta == '-exp-latest_pages-page_7'){
            $cblock->subject = t("By group"); 
        }
    }
    
}

function mt_ds_fields($type_name, $build_mode, $extra) {
  $fields = array(
    'mt_event_image' => array(
      'title' => t('Image'),
      'exclude' => array(
        'group' => 'group',
        'link' => 'link',
        'webform' => 'webform',
        'article' => 0,
        'audio' => 0,
        'event' => 0,
        'feeds' => 0,
        'file' => 0,
        'nnews' => 0,
        'npage' => 0,
        'place' => 0,
        'video' => 0,
        'gallery' => 0,
        'gallery_image' => 0,
        'forum' => 0,
        'taxonomy_feature' => 0,
      ),
      'type' => DS_FIELD_TYPE_CODE,
      'status' => DS_FIELD_STATUS_CUSTOM,
      'properties' => array(
        'css-class' => 'field-nodes-slideshow',
        'formatters' => array(
          'ds_eval_code' => 'Default',
        ),
        'code' => '<?php 
          print mt_event_image($object);
        ?>',
        'token' => 0,
      ),
    ),
  );

  return array('nd' => $fields);
}

function mt_event_image($node){
  if(count($node->field_list_image)>0 && isset($node->field_list_image['0']['fid'])){
    return views_embed_view("node_details","block_2", $node->nid);
  }
  else{
    $gid = array_pop($node->og_groups);
    return views_embed_view("node_details","block_2", $gid);
  }
}

function mt_form_alter(&$form, &$form_state, $form_id){
  if ($form['#id'] == 'node-form') {
    if($form['og_nodeapi']['visible']['og_groups']['#options']['0']=='- None -'){
      unset($form['og_nodeapi']['visible']['og_groups']['#options']['0']);
    }
    if (isset($form['locations'][0]) && $form['locations'][0]['#default_value']['province']=='NY' && $form['locations'][0]['#default_value']['city']=='Harlem' ) {
      $form['locations'][0]['#default_value'] = array(
        'city' => '',
        'province' => 'FL',
        'country' => 'us'
      );
    }
  }
}



function mt_feedapi_mapper($op, $node, $feed_element = array(), $field_name = '', $sub_field = '') {
  if ($op == 'describe') {
    return t('Maps a string or an array of strings to myfields.');
  }
  else if ($op == 'list') {
    $myfields = array('event' => array(
      'start' => 'start',
      'end' => 'end',
    ));
    return $myfields;
  }
  else if ($op == 'map') {
      if ($field_name == 'event') {
        if (is_string($feed_element)) {
          $node->event[$sub_field] = $feed_element;
          $node->event['has_time'] = '1';
          $node->event['dst_region'] = '115';
          $node->event['has_end_date'] = '1';
          $node->event['offset'] = ' -05:00:00';
          $node->event['offset_dst'] = '-04:00:00';
          $node->event['timezone'] = '119';
          $node->event[$sub_field . '_exploded']['year'] = date('Y', strtotime($feed_element));
          $node->event[$sub_field . '_exploded']['month'] = date('m', strtotime($feed_element));
          $node->event[$sub_field . '_exploded']['day'] = date('d', strtotime($feed_element));
          $node->event[$sub_field . '_exploded']['hour'] = date('G', strtotime($feed_element));
          $node->event[$sub_field . '_exploded']['minute'] = date('i', strtotime($feed_element));
          $node->event[$sub_field . '_exploded']['second'] = date('s', strtotime($feed_element));
        }
      return $node;
    }
  }
}
