<?php

include_once('ft_place.features.inc');

function ft_place_preprocess($vars,$hook){
    if($hook == 'block'){
        $cblock = $vars['block'];
        if($cblock->module == 'ds' && $cblock->bid == 'ds-bf71adff8bdebc9c46bf7e6772aa3eca'){
            $cblock->subject = t("Where it's at"); 
        }
    }
}

function ft_place_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  if($node->type != "place"){
    return; //exit function
  }

  switch($op){
    case 'presave':
      if(!empty($node->title) && (!$node->title != $node->locations[0]['name'])){
        $node->locations[0]['name'] = $node->title;
      }
    break;
  };
};

function ft_place_late_form_alter(&$form, &$form_state, $form_id){

  $path = drupal_get_path("module","ft_place");

  if(!is_ct_form($form,'place')){
      return;
  }

  global $user;

  //hide group_hideus and taxonomy fieldset
  if($user->uid > 1){
    $form['group_hideus']['#access'] = false;
    $form['taxonomy']['#access'] = false;
    $form['body_field']['#access'] = false;
    drupal_add_css($path . "/ft_place.css");
  }

  $form['field_list_image']['#title'] = "Photos";
  $form['field_list_image']['#description'] = t("Add photos for this place. The first photo will be used as the main photo for this place.");
}