<?php

include_once('ft_place.features.inc');

function ft_place_preprocess($vars,$hook){
    if($hook == 'block'){
        $cblock = $vars['block'];
        if($cblock->module == 'ds' && $cblock->bid == 'ds-bf71adff8bdebc9c46bf7e6772aa3eca'){
            $cblock->subject = t("Where it's at"); 
        }
    }
}


function ft_place_late_form_alter(&$form, &$form_state, $form_id){
  if(!is_ct_form($form,'place')){
      return;
  }

  global $user;

  dsm($form);
  formfilter_filter_form($form,array(
     array('group_hideus')
  ));

  if($user > 0){
    $form['group_hideus']['#access'] = false;
  }

}