<?php
/**
 * @file
 * Code for the Feature Rating feature.
 */

include_once 'mc_rating.features.inc';

function mc_rating_theme(){
  return array(
    'rate_template_mc_up_down' => array(
      'arguments' => array('links' => NULL, 'results' => NULL, 'mode' => NULL, 'just_voted' => FALSE, 'content_type' => NULL, 'content_id' => NULL),
      'template' => 'mc-up-down',
      'path' => drupal_get_path('module', 'mc_rating') . '/widgets/mc-up-down',
    ),
  );
}

/**
 * Implements hook_rate_templates().
*/
function mc_rating_rate_templates() {
  $templates = array();
  $templates['mc_up_down'] = new stdClass();
  $templates['mc_up_down']->value_type = 'points';
  $templates['mc_up_down']->options = array(
    array(1, 'up'),
    array(0, 'reset'),
    array(-1, 'down'),
  );
  $templates['mc_up_down']->theme = 'rate_template_mc_up_down';
  $templates['mc_up_down']->css = drupal_get_path('module', 'mc_rating') . '/widgets/mc-up-down/mc-up-down.css';
  $templates['mc_up_down']->js = drupal_get_path('module', 'mc_rating') . '/widgets/mc-up-down/mc-up-down.js';
  $templates['mc_up_down']->customizable = FALSE;
  $templates['mc_up_down']->translate = TRUE;
  $templates['mc_up_down']->template_title = t('MC: Thumbs up / down');

  return $templates;
}

function mc_rating_preprocess_rate_template_mc_up_down(&$variables) {
  $buttons = $variables['links'];
  $rate = $variables['results']['rating'];

  foreach($buttons as $key => &$btn){
    $btn['active'] = $btn['value'] == $rate ? 1 : 0;
    $btn['class'] = $btn['value'] == $rate ? " btn-active" : "";

    //if $key == 1 and active (no rating, then hide the button)
    if($btn['active']){
      //means no values exists.. hide this button
      $btn['class'] .= " btn-hide";
    }
  }

  //change icon or rest depends on the current value btn[1] = reset button
  switch($rate){
    case '-1':
      $buttons[1]['class'] = " rate-reset rate-down btn-active";
      break;
    case '1':
      $buttons[1]['class'] = " rate-reset rate-up btn-active";
      break;
  }

  $variables['buttons_updown'] = array(
    '0' => theme('rate_button', $buttons[0]['text'], $buttons[0]['href'], 'rate-btn rate-up' . $buttons[0]['class']),
    '1' => theme('rate_button', $buttons[1]['text'], $buttons[1]['href'], 'rate-btn' . $buttons[1]['class']),
    '2' => theme('rate_button', $buttons[2]['text'], $buttons[2]['href'], 'rate-btn rate-down' . $buttons[2]['class'])
  );

}
