<?php

define("MC_OG_MENU_DEFAULT",'og_posts');

function _mc_og_menu_items(){
  return array(
    'home' => array(
      'title' => 'Latest',
      'link' => 'node/!nid'
    ),
    'about' => array(
      'title' => 'About',
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_1',
      'link' => 'node/!nid/about',
      'is_menu_item' => TRUE
    ),
    'latest' => array(
      'title' => 'Latest',
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_1',
      'link' => 'node/!nid/latest',
      'is_menu_item' => TRUE
    ),
    'events' => array(
      'title' => "Events",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_4',
      'link' => 'node/!nid/events',
      'is_menu_item' => TRUE
    ),
    'articles' => array(
      'title' => "Articles",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_5',
      'link' => 'node/!nid/articles',
      'is_menu_item' => TRUE
    ),
    'files' => array(
      'title' => "Files",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_6',
      'link' => 'node/!nid/files',
      'is_menu_item' => TRUE
    ),
    'photos' => array(
      'title' => "Photos",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_7',
      'link' => 'node/!nid/photos',
      'is_menu_item' => TRUE
    ),
    'discussions' => array(
      'title' => "Discussions",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_8',
      'link' => 'node/!nid/discussions',
      'is_menu_item' => TRUE
    ),
    'videos' => array(
      'title' => "Videos",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_8',
      'link' => 'node/!nid/videos',
      'is_menu_item' => TRUE
    ),
    'contact' => array(
      'title' => "Contact",
      'link' => 'node/!nid/videos'
    )
  );
}

function og_prepopulate_menu_menu(){
  $items = array();

  $menu_list = _mc_og_menu_items();
  foreach($menu_list as $key => $item){
    if($item['is_menu_item']){
      $view = $item['view'];
      $display = $item['display_id'];
      $path = t($item['link'],array('!nid' => '%node'));
      $items[$path] = array(
        'title' => $item['title'],
        'page callback' => '_mc_load_view_page',
        'page arguments' => array(1,$item),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
      );
    }
  }

  return $items;
}

/**
 * mc_og_menu page callback
 * @param $node current og node
 * @param $item menu item from _mc_og_menu_items()
 * @return bool|void
 */
function _mc_load_view_page($node,$item){
  $view = $item['view'];
  $display = $item['display_id'];

  if(og_is_group_type($node->type)){
    return views_embed_view($view,$display);
  }

  return drupal_not_found();
}

function _og_prepopulate_menu_create_custom_menu($node){
  $menu_name = 'menu-og-' . $node->nid;
  $sql = "SELECT COUNT(*) FROM {menu_custom} WHERE menu_name = '%s'";
  if (db_result(db_query($sql, $menu_name))){
    // already created
    return;
  }
  $title = t('GROUP') . ' - ' . $node->title;
  $description = t('Menu created automatically for group: ' . $node->title);
  $sql = "INSERT INTO {menu_custom} (menu_name, title, description) VALUES ('%s', '%s', '%s')";
  db_query($sql, $menu_name, $title, $description);
}