<?php
/**
 * @file
 * Code for the mt_userflow feature.
 */

include_once 'mt_userflow.features.inc';


function mt_userflow_user($op, &$edit, &$account, $category = NULL){
	if($op == "login"){
		
	}
}

function rules_comment_view($comment) {
  rules_invoke_event('comment_view', $comment);
}

function comment_rules_event_info() {
  $defaults = array(
    'group' => t('user'),
    'module' => 'mt_userflow'
  );
  return array(
    'comment_insert' => $defaults + array(
      'label' => t('After saving a new comment'),
      'variables' => array(
        'comment' => array('type' => 'comment', 'label' => t('created comment')),
      ),
    ),
  );
}