<?php
/**
 * @file
 * Code for the mt_userflow feature.
 */

include_once 'mt_userflow.features.inc';


function mt_userflow_message_alter(&$messages){
		global $user;
		$udata = unserialize($user->data);
		if($udata['updatedprofile'] == 1){
			$matches = $messages->contains('The changes have been saved','status');
			$messages->remove($matches);
		}
}


function mt_userflow_late_form_alter(&$form, &$form_state, $form_id){
  global $user;

  if($form['#id'] == "node-form"){
    //current node
    $node = $form['#node'];

    //check if you are adding new node and have no group associated with the current user
    if(!$node->nid && $node->type != "group" && !mt_count_user_ct('group')){
       drupal_set_message("Woops, please add a group first.");
       drupal_goto('node/add/group');
    }
  }
}