<?php

/**
 * @todo add the correct classes to the page (maybe use context as well)
 * #todo display suite url not to be accessable though any other node but webform http://local.sje.mycommunity.org/admin/content/node-type/webform/display/mc_og_forms
 *
*/

//default value for var: mc_og_forms_contact_nid
define('MC_OG_FORMS_CONTACT_NID_DEFAULT',989);

function _mc_og_forms_theme(){
  return array(
    'mc_og_forms_contact' => array(
      'arguments' => array('forums' => NULL, 'topics' => NULL, 'parents' => NULL, 'tid' => NULL, 'sortby' => NULL, 'forum_per_page' => NULL),
      //'template' => 'og-form-contact',
    ),
  );
}

function mc_og_forms_contact($form_stats,$nid){

  $form = array();

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => "Your Name",
    '#required' => true
  );

  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => "Your E-mail",
    '#required' => true
  );

  $form['subject'] = array(
    '#type' => 'textfield',
    '#title' => "Subject",
    '#required' => true
  );

  $form['message'] = array(
    '#type' => 'textarea',
    '#title' => "Message",
    '#required' => true
  );

  $form['nid'] = array('#type' => 'value', '#value' => $nid);

  $form['submit'] = array('#type' => 'submit', '#value' => t('Submit'));

  $form['#redirect'] = 'node/'.$nid;

  return $form;
}

function mc_og_forms_contact_submit($form, &$form_state){
  //fields
  $fields = array('name','email','subject','message');

  $nid = $form_state['values']['nid'];
  $node = node_load($nid);

  drupal_set_message(
    t("Thank you for contacting !gname! We'll be in touch shortly.",array(
      '!gname' => l($node->title,"node/".$node->nid)
    ))
  );
}

function is_mc_og_form_contact($node){
  if(variable_get("mc_og_forms_contact_nid",MC_OG_FORMS_CONTACT_NID_DEFAULT) == $node->nid){
    return true;
  }
  return false;
}

/**
 * hook_menu
 * @return array
 * @see http://api.drupal.org/api/drupal/developer%21hooks%21core.php/function/hook_menu/6
 */
function mc_og_forms_menu(){
  $items['node/%node/contact'] = array(
    'title' => 'Contact',
    'page callback' => '_mc_og_forms_contact',
    'page arguments' => array(1),
    'access callback' => '_mc_og_forms_access',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * check if the current node is group node
 * @param $node
 * @return bool
*/
function _mc_og_forms_access($node){
  return og_is_group_type($node->type);
}

/**
 * node/%og/contact callback function
 * @param $node
 * @return mixed|string
 */
function _mc_og_forms_contact($node){
  return drupal_get_form("mc_og_forms_contact",$node->nid);
}