<?php
/**
 * @file
 * Code for the Feature Page General feature.
 */

include_once 'ft_page_general.features.inc';

function ft_page_general_menu(){
  $items['admin/settings/mcabout'] = array(
    'title' => 'MC Default About Page',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_mc_page_general_default_about'),
    'access arguments' => array('administer users'),
  );
  return $items;
}

function _mc_page_general_default_about(&$form_state) {
  $domain = $_SERVER['HTTP_HOST'];
  $form = array();
  $form['mc_default_about'] = array(
    '#type' => 'textfield',
    '#title' => t('MC Default About Page'),
    '#default_value' => variable_get('mc_default_about_nid' ,''),
    '#required' => TRUE,
    '#description' => t('Please specify the nid of the about node'),
    '#field_prefix' => '<span class="field-prefix">http://'. $domain . '/node/</span>',
  );
  $form = system_settings_form($form);
  unset($form['#submit']);
  $form['#submit'] = array('_mc_page_general_default_about_submit');
  return $form;
}

function _mc_page_general_default_about_submit($form, &$form_state) {
  $alias = 'about';
  $language = '';
  $existing = db_fetch_array(db_query("SELECT src, language, pid FROM {url_alias} WHERE dst = '%s' AND language IN('%s', '') ORDER BY language DESC, pid DESC", $alias, $language));
  if ($existing) {
    path_set_alias(null, null, $existing['pid']);
  }
  $nid = $form_state['values']['mc_default_about'];
  variable_set('mc_default_about_nid', $nid, '', '');
  path_set_alias('node/'.$nid , 'about');
}


/*
 * The view mc_page_menu is in the feature ft_landing_contexts.
 */
function ft_page_general_views_query_alter(&$view, &$query){
  if($view->name=='mc_page_menu' && $view->current_display=='block_1'){
    $view->display['block_1']->handler->handlers['field']['title']->query->table_queue['draggableviews_structure_node0']['join']->extra[1]['value'] = 'mc_page_menu_admin';
  }
}