<?php

function github_deploy_menu(){
 $items = array();

      $items['github/deploy'] = array(
        'title' => 'github deploy',
        'page callback' => '_github_deploy',
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK
      );

    return $items;
}

function exec_enabled() {
    $disabled = explode(', ', ini_get('disable_functions'));
    return !in_array('exec', $disabled);
}

function mc_deploy_form_settings(){
  $form = array();

  $form['mc_deploy_ssh_host'] = array(
    '#type' => 'textfield',
    '#title' => t('SSH Host'),
    '#default_value' => variable_get("mc_deploy_ssh_host","")
  );

  $form['mc_deploy_shh_user'] = array(
          '#type' => 'textfield',
          '#title' => t('SSH User Name'),
          '#default_value' => variable_get("mc_deploy_shh_user","")
  );

  $form['mc_deploy_ssh_pass'] = array(
           '#type' => 'textfield',
           '#title' => t('SSH Password'),
           '#default_value' => variable_get("mc_deploy_ssh_pass","")
  );

  return system_settings_form($form);
}

function _github_deploy(){
    //dsm(realpath('.'));
    //dsm(conf_path());

    set_time_limit(120);
    $sitepath = realpath('.');
    $sitepath = "/home/www/miamitech/dev.miamitech.org/htdocs";
    $current_site = $sitepath ."/".conf_path();
    dsm($current_site);
    $output = shell_exec("cd $current_site; drush cc all", $output);
    dsm($output);

    return 'Done Excuting deploy';
}