<?php
/**
 * @file
 * Code for the mc_twitter feature.
 */

include_once 'mc_twitter.features.inc';

function twitter_account_load_byscreename($screen_name){
  $id = db_result(db_query("SELECT twitter_uid FROM {twitter_account} WHERE screen_name = '%s'",$screen_name));
  if($id){
    return twitter_account_load($id);
  }

  return false;
}

function mc_tweet($account,$status,$log = true){
  if(!empty($acount) && !is_object($account)){ //if it's not object, then try to load the user and not empty
    if(intval($account)){ //if it's valid intval, use it to load the account
      $account = twitter_account_load($account);
    }else{//load it by name
      $account = twitter_account_load_byscreename($account);
    }
  }

  try {
    twitter_set_status($account,$status);
    return true;
  }
  catch (TwitterException $e) {
    //@todo convert to watchdog instead of drupal_set_message
    drupal_set_message(t('An error occurred when posting to twitter: %code %error',
      array('%code' => $e->code, '%error' => $e->error)), 'warning');
    return false;
  }
}