<?php



function mc_addstuff_block($op = 'list', $delta = 0, $edit = array()) {
    
  if ($op == 'list') {
    
    $blocks[0] = array(
      'info' => t('Add Stuff block'), 
      'weight' => 0, 
      'status' => 1,
      'cache' => BLOCK_CACHE_PER_ROLE | BLOCK_CACHE_PER_PAGE
    );
    return $blocks;
    
  }else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => '', 
          'content' => mc_addstuff_display_block_add_stuff(),
        );
        break;
    }
    return $block;
  }
  
}



/**
 * Block content callback. Retrieves the list of content types that are group posts and display them in a group.
 */
function mc_addstuff_display_block_add_stuff(){
  global $user;
  
  // check if og is configured properly
  $is_configured = count(og_get_types('group')) && count(og_get_types('group_post'));
  if (!$is_configured) {
    form_set_error('content_types_table', t('You must designate at least one content type to act as a group node and another as a group post. <a href="!create">Create new content type</a> if needed.', array('!create' => url('admin/content/types/add', array('query' => drupal_get_destination())))));
  }
  
  $map = og_types_map();
  
  $rows = array();
  
  // get node types and sort them by name
  $types = node_get_types();
  usort($types, '_mc_addstuff_sort_by_name');
  
  // if in a node page, load node
  $node = NULL;
  if (arg(0) == 'node' && is_numeric(arg(1))){
    $node = node_load(arg(1));
  }
  
  $add_stuff_types = array('article', 'event', 'gallery_image', 'gallery', 'audio', 'video', 'place', 'file', 'npage', 'group', 'forum','event_feed');
  $add_stuff_types = array_keys(node_get_types('types'));
  //dsm($add_stuff_types);
  //dsm(node_get_types('types'));


  foreach ($types as $type) {

    if (!in_array($type->type, $add_stuff_types)){
      continue;
    }
    
    $type_url_str = str_replace('_', '-', $type->type);
    $usage = variable_get('og_content_type_usage_'. $type->type, 'omitted');
    
    $addLink = FALSE;
    $addLinkDestination = FALSE;
    $addLinkOptions = array();
    
    // Check if we should add to a group
    $group = og_get_group_context();
    if ($group == NULL){
      if (arg(0) == 'node' && is_numeric(arg(1))){
        $group = og_determine_context_get_group(node_load(arg(1)));
      }elseif (arg(0) == 'node' && arg(1) == 'add' && is_numeric(arg(3))){
        $group = og_determine_context_get_group(node_load(arg(3)));
      }
    }
    
    // Anonymous, will see add stuff containing links to the register page
    if (!$user->uid){
      if(user_access('add stuff ' . $type->type )){
        // show them only the types that can be posted in a group (except page and album)
        
          //$addLink = 'user/register';
          $addLink = "node/add/$type_url_str";
          $addLinkOptions['query']['type'] = $type_url_str;
          if (is_object($group)){
            $addLinkDestination = "node/add/$type_url_str/" . $group->nid;
          }else{
            $addLinkDestination = "node/add/$type_url_str";
          }
          if ($type->type != 'gallery_image'){
            $addLinkOptions['query']['destination'] = $addLinkDestination;
            //$addLinkOptions['query']['destination'] = $_GET['destination'];
          } 
          $addLinkOptions['query']['message'] = 'register-first';  
        
      }
    
    // check if the user has permissions to create this type of node
    }elseif (user_access("create " . $type->type . " content") || ($type->type=='forum' && user_access("create forum topics"))){
      if(user_access('add stuff ' . $type->type )){
      // TODO: Fix this hack, it's really ugly 
      // Since we are using nodereference_url alread for the gallery-image type, 
      // we need to find a way for the user to choose the gallery, so we redirect
      // them to the galleries page, and just display a messsage with instructions
      if ($type->type == 'gallery_image'){
      
        if ($node && $node->type == 'gallery'){
          $addLink = "node/add/$type_url_str/" . $node->nid;
        }elseif ($node && $node->type == 'gallery_image'){
          $addLink = "node/add/$type_url_str/" . $node->field_gallery[0]['nid'];
        }else{
          
          if($usage == 'group_post_standard' && is_object($group)){
            $addLink = $group->path . '/photos';
          }else{
            $addLink = $_GET['q'];
          }
                    
          $addLinkOptions['query']['message'] = 'choose-gallery';
            
        }
      
      }else{
        
        if($usage == 'group_post_standard' && is_object($group)){
          $addLink = "node/add/$type_url_str/" . $group->nid;
        }else{
          $addLink = "node/add/$type_url_str";
        }
        
        
      }
    }
      
    // No anonymous, no permissions, continue with next content type
    }else{
      continue;
    }
    
    if ($addLink){
      
      $rows[$type->name] = array(
        'title' => '<span class="ico-add-stuff ico-'. $type->type .'" ></span><span class="add-stuff-name">' . $type->name . '</span>',
        'html' => true,
        'href' => $addLink,
      );
      if (!empty($addLinkOptions)){
        $rows[$type->name] += $addLinkOptions;
      }
    }
  }

  $output = theme('links', $rows);
  return $output;

}

function mc_addstuff_init(){
  $message = $_GET['message'];
  if ($message == 'choose-gallery'){
    drupal_set_message(t('To add a photo, please first find an album and then try again. We try to keep things organized around here!'), 'strong-status');
  }elseif ($message == 'register-first'){
    $login_link = l(t('sign in'), 'user/login', array( 'query' => array('destination' => $_GET['destination']) ) );
    $join_link = l(t('join now'), 'user/register', array( 'query' => array('destination' => $_GET['destination']) ) );
    drupal_set_message(t("We're just thrilled that you'd like to add stuff, but please first $login_link or join now below."), 'strong-status');
  }
}

function _mc_addstuff_sort_by_name($a, $b) {
  if ($a->name == $b->name) {
    return 0;
  } else {
    return $a->name < $b->name ? -1 : 1;
  }
}


/**
 * Implementation of hook_boot()
 */
function mc_addstuff_boot(){
  global $user;
  
  if ($user->uid != 0 && isset($_GET['message']) && $_GET['message']=='register-first'){
    unset($_GET['message']);
  }
  if(isset($_GET['q'])){
    $arg = explode('/', $_GET['q']);
    if((!isset($user->uid) || $user->uid=='0') && $arg[0]=='node' && $arg[1]=='add' ){
      if (isset($_GET['type'])){
        if ($_GET['message']=='register-first'){
          header('Location: http://' .$_SERVER['HTTP_HOST'] .'/user/register?type=' . $_GET['type'] . '&message=register-first');
        }else{
          header('Location: http://' .$_SERVER['HTTP_HOST'] .'/user/register?type=' . $_GET['type']);
        }
      }else{
        header('Location: http://' .$_SERVER['HTTP_HOST'] .'/user/register?message=register-first');
      }
      exit();
    }
  }
}
 

function mc_addstuff_perm(){
  $perms = array();
  $types = node_get_types();
  foreach ($types as $type) {
    $perms[] = 'add stuff ' . $type->type;
  }
  return $perms;
}