<?php

function features_perm_settings_form(){
    $form['features_perm_module'] = array(
        '#title' => t('Export all permissions and roles to this module'),
        '#type' => 'textfield',
        '#description' => t('enter the module name here'),
        '#default_value' =>  variable_get("features_perm_module","")
    );

    return system_settings_form($form);
}

function features_perm_menu(){

    $items['admin/build/features/feature_permissions'] = array(
        'title' => 'Features Permission Helper',
        'type' => MENU_NORMAL_ITEM,
        'page callback' => 'drupal_get_form',
        'page arguments' => array("features_perm_settings_form"),
        'access arguments' => array('administer features'),
        'weight' => 100
    );

    return $items;
}

function features_perm_features_export_alter(&$export, $module_name) {
    module_load_include("inc", "features", "includes/features.user");

	if($module_name == variable_get("features_perm_module","")){
        //User roles
        $roles = user_role_features_export_options();
        foreach($roles as $role => $title){
            $export['features']['user_role'][$role] = $role;
        }

        //User Permissions
        $perms = user_permission_features_export_options();
        foreach($perms as $perm => $title){
            $export['features']['user_permission'][$perm] = $perm;
        }
	}
}