<?php

function _semanticviews_class_to_attr($attr = array(),$what = 'class'){
  $ptn = "({(.*?)})";

  if(!empty($attr[$what])){
    $cls = &$attr[$what];

    preg_match($ptn,$cls,$matchs);

    if(count($matchs) > 1){
      $cls = trim(preg_replace($ptn,"",$cls));
      parse_str($matchs[1],$new_attr);
      $attr = array_merge($attr,$new_attr);
    }
  }

  return $attr;
}

function semanticviews_plus_theme_registry_alter(&$theme_registry){
  $themes = array("semanticviews_view_unformatted","semanticviews_view_fields");
  $module_loc = drupal_get_path("module",'semanticviews_plus');

  foreach($themes as $theme){
    if(isset($theme_registry[$theme])){
      $theme_registry[$theme]['theme paths'][] = $module_loc;
    }
  }

}

function semanticviews_plus_preprocess_semanticviews_view_unformatted(&$vars){

  if(!empty($vars['group_attributes'])){
    $vars['group_attributes'] =  _semanticviews_class_to_attr($vars['group_attributes']);
  }

  if(!empty($vars['list_attributes'])){
    $vars['list_attributes'] =  _semanticviews_class_to_attr($vars['list_attributes']);
  }

  if(!empty($vars['row_attributes'])){
    foreach($vars['row_attributes'] as &$attr){
      $attr = _semanticviews_class_to_attr($attr);
    }
  }

}

function semanticviews_plus_preprocess_semanticviews_view_fields(&$vars){
  //parse querystring at classes and turn them into regular attributes
  //example: class-name {attr1=2&attr3=5} >> <tag class="class-name" attr1="2" attr3="5"></tag>

  foreach($vars['fields'] as &$field){
    if(!empty($field->attributes)){
      $field->attributes = _semanticviews_class_to_attr($field->attributes);
    }
  }
}
