<?php

/*
 * @todo: https://app.asana.com/0/1947405877174/1947670111015
 */
function mc_base_helper_jqmulti_libraries(){
  return array(
    "qtip2"//,'jquery.cookie.js'
  );
}

function mc_base_helper_init(){
  $lib = libraries_get_path("qtip2");
  if(!empty($lib)){
    drupal_add_js($lib."/".'jquery.qtip.min.js');
    drupal_add_css($lib."/".'jquery.qtip.min.css');
  }

  $lib = libraries_get_path("jquery.cookies");
  drupal_add_js($lib."/".'jquery.cookie.js');
}

function mc_base_helper_preprocess_page(){

  if(!module_exists('conditional_styles')){
	drupal_set_message('The module conditional_styles must be enabled for the theme to work properly.');
  }

  if(!module_exists('jqmulti')){
    drupal_set_message('The module jqmulti must be enabled for the theme to work properly.');
  }
}
