<?php

include_once('ft_news.features.inc');

function ft_news_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL){
  if($node->type == "nnews"){
    switch($op){
      case 'presave':
        //strip tags from news item title
        if(!empty($node->title)){
            $node->title = strip_tags($node->title);
        }
        break;
    }
  }
}

function ft_news_block($op = 'list', $delta = 0, $edit = array()) {
  switch($op){
    case 'list':
      $blocks['news-sideblock'] = array(
        'info' => t('News: Sideblock'),
        'weight' => 0,
        'status' => 1,
      );
      return $blocks;
      break;
    case 'view':
      switch ($delta) {
        case 'news-sideblock':
          $block = array(
            'subject' => '',
            'content' => _news_sidebock(),
          );
          break;
      }
      return $block;
      break;
  }
}

function _news_sidebock(){
  global $user;

  $links = array();
  $links[] = l("<span class=\"rss-group-ico ico-inline\"></span>News RSS feed","news/feed",array("html"=>true));

  return theme("item_list",$links,null,'ul',array('class'=>"mc-links-blue"));
}