<?php

/*
 * @todo fix for jquery_update missing constant that needed for ctools
 * @see http://drupal.org/node/1067290#comment-6208188
 */
define('JQUERY_UPDATE_REPLACE_PATH', drupal_get_path('module', 'jquery_update') .'/replace');


function ctools_ajax_command_select2_val($selector,$nid,$val,$val_title) {
  return array(
    'command' => 'select2_val',
    'selector' => $selector,
    'value' => $val,
    'value_title' => $val_title,
    'nid' => $nid
  );
}

/*
 * @todo remove misc/autocomplete.js through hooks instead of manually removing the file.
 * @todo imrpove the speed and logic of auto-complete callback
 * @todo use the hooks of jqmulti to add the jq1.8 dependecies
 * @todo avoid hacking line 978 @ nodereference.module
 * @todo package jquery_update options at http://w.miamitech.org/admin/settings/jquery_update
 * @todo find a fix for the drupal_to_json fix @ includes.inc
*/

function select2_init(){
  $path = drupal_get_path("module",'select2');
  $lib = libraries_get_path("select2");

  _add_node_form();

  /*
   * add required select2 files
  */
  drupal_add_js($lib."/select2.min.js");
  drupal_add_css($lib."/select2.css");

  /*
   * add select2 auto-complete behaviour, overrides the current drupal auto-complete
  */
  drupal_add_js($path."/select2.js");
}


function select2_menu(){
  $items = array();

  $items['select2/autocomplete'] = array(
    'page callback' => '_select2_autocomplete',
    'access arguments' => array('access content'),
    'type' => MENU_SUGGESTED_ITEM,
  );

  $items['select2/%ctools_js/add/%'] = array(
    //'title' => 'Login',
    'page callback' => 'modal_forms_login',
    'page arguments' => array(1,3,4),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/*
 * Converts drupal default auto-complete response to an array of objects, {id: "",text:"","nid": "if nodereference"}
 */
function _drupal_ac_to_object($vals,$is_nr = false){
  $vals_ob = array();

  if(!empty($vals)){
    foreach($vals as $key => &$val){
      $val_ob = new stdClass();
      $val_ob->id = $key;

      //parse back the string as it was before it passed through check_plain
      $val_ob->text = html_entity_decode(strip_tags($val),ENT_QUOTES,'UTF-8');

      if($is_nr){
        //parse node id and attach it to the select data for easier access on the client side
        preg_match('/^(?:\s*|(.*) )?\[\s*nid\s*:\s*(\d+)\s*\]$/', $val_ob->id, $matches);
        if (!empty($matches)) {
          // Explicit [nid:n].
          list(, $title, $nid) = $matches;
          $val_ob->nid = $nid;
        }
      }

      array_push($vals_ob,$val_ob);
    }
  }

  return $vals_ob;
}

function _select2_autocomplete(){
  $url = $_GET['url'];
  $term = $_GET['term'];
  $field_id = $_GET['field_id'];

  $fullpath = $url."/".$term;

  //detect and remove the host, clean up the first backslash
  $url_parse = parse_url($fullpath);
  $real_path = ltrim($url_parse['path'],"/");

  //change the url to become the real autocomplete path
  $_GET['q'] = $real_path;

  //start capturing output events
  ob_start();
  menu_execute_active_handler();
  $output = ob_get_clean();

  //decode the values that you got from ob_get_clean
  $vals = json_decode($output,true);

  //starting the response object
  $ob = new stdClass();
  $ob->term = $term;
  $ob->input_id = $_GET['field_id'];
  $ob->custom = false;

  if(arg(0) == 'nodereference'){
    $ob->cck_field = arg(2);
    $ob->is_nr = true;
  }else{
    $ob->is_nr = false;
  }

  //convert the drupal ac json response to object of arrays
  $ob->vals = _drupal_ac_to_object($vals,$ob->is_nr);

  //output the response object
  print drupal_json($ob);
  exit();
}

function _add_node_form(){
  static $already_added = FALSE;

  //adding bootstrap js

  // Include the CTools tools that we need.
  ctools_include('ajax');
  ctools_include('modal');

  // Add CTools' javascript to the page.
  ctools_modal_add_js();

  $js_settings = array(
    'modal-popup-small' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 600,
        'height' => 600,
        'addWidth' => 0,
        'addHeight' => 0,
        'contentRight' => 0,
        'contentBottom' => 0
      ),
      'modalOptions' => array(
        'opacity' => 0.85,
        'background' => 'gray',
      ),
      'animation' => 'show',
      'closeText' => t('Close'),
    ),

  );

  drupal_add_js($js_settings, 'setting');
}

function modal_forms_login($js = NULL,$ct = NULL,$input_id) {
  global $user;

  /*
   * @todo add logic if it's not js callback, maybe simply redirect to the add form page.
   */

  ctools_include('node.pages','node',"");

  //set up a dummy node to make sure the form comes in right
  $node_form = $ct."_node_form";
  $node = new stdClass();
  $node->uid = $user->uid;
  $node->type = $ct;
  node_object_prepare($node);

  // Fall back if $js is not set.
  if (!$js) {
    return drupal_get_form($node_form,$node);
  }

  ctools_include('modal');
  ctools_include('ajax');

  //@todo change the title to the content type human name
  $form_state = array(
    'title' => t('Add New ' . $ct),
    'ajax' => TRUE,
    'args' => array($node)
  );

  $output = ctools_modal_form_wrapper($node_form, $form_state);

  if (!empty($form_state['executed'])) {

    //initiate the output ajax command array
    $output = array();

    //the new node that has been created
    $nid = $form_state['nid'];

    //return the new node id back to the select list
    if($nid){
      // @todo change the selectlist list to the newly created content type.
      $node = node_load($nid);
      $val = $node->title . " [nid:$node->nid]";
      $output[] = ctools_ajax_command_select2_val($input_id,$nid,$val,$node->title);
    }

    // We'll just overwrite the form output if it was successful.
    ctools_add_js('ajax-responder');
    //$output[] = ctools_modal_command_dismiss(t('Login Success'));

  }

  //render output array/string to back to drupal
  print ctools_ajax_render($output);
  exit;
}