<?php

require_once ( dirname(__FILE__) . '/feedapi_mc.inc');

function feedapi_mc_nodeapi(&$node, $op, $teaser) {
  switch($op){
    case 'presave':
      $drupal_path = drupal_get_normal_path($_GET['q']);
      if($node->type=='event' && isset($node->nid) && ($drupal_path=='batch' || (arg(0, $drupal_path)=='node' && arg(2, $drupal_path)=='edit' && is_numeric(arg(1, $drupal_path)) && arg(1, $drupal_path)==$node->nid))){
        $query = "UPDATE feedapi_node_item SET updatable=0 WHERE nid=" . $node->nid;
        db_query($query);
        $query = "UPDATE feedapi_node_item SET update_date=" . time() . " WHERE nid=" . $node->nid;
        db_query($query);
      }
      break;
    case 'prepare':
      $drupal_path = drupal_get_normal_path($_GET['q']);
      $is_same_node = arg(1, $drupal_path)==$node->nid;
      if($node->type=='event' && $is_same_node && isset($node->feedapi_node) && is_object($node->feedapi_node)){
        if(isset($node->nid) && _feedapi_mc_is_updatable($node->nid)){
          drupal_set_message('This event was automatically created from a feed. If you apply manual edits, we will stop updating it automatically.');
        }
        if(isset($node->nid) && !_feedapi_mc_is_updatable($node->nid)){
          $unixdate = _feedapi_mc_get_update_date($node->nid);
          $date = date('M j, Y g:iA', $unixdate);
          drupal_set_message('This event was manually edited on ' . $date . '. Automatic updates from its feed are no longer being applied.');
        }
      }
      break;
    default:
      break;
  }
}

