<?php

include_once('ft_location.features.inc');


function ft_location_ds_fields_alter(&$fields) {
  $fields['nd_directions']['properties']['formatters']['mt_location_directions'] = 'MT Format';
  $fields['nd_location_name'] = $fields['name'];
  $fields['nd_location_name']['properties']['formatters']['mt_location_textfield'] = t('MT Textfield');
  unset($fields['name']);

  unset($fields['nd_location_gmap']['properties']['formatters']['nd_location_gmap_default']);
  $fields['nd_location_gmap']['properties']['formatters']['mt_location_gmap_default'] = 'Gmap MT';
}


function ft_location_theme() {
  $theme_functions = array(
    'mt_location_textfield' => array(
      'arguments' => array('field' => NULL),
    ),
    'mt_location_gmap_default' => array(
      'arguments' => array('field' => NULL),
    ),
    'mt_location_directions' => array(
      'arguments' => array('field' => NULL),
    ),
  );
  return $theme_functions;
}

function theme_mt_location_directions($field) {
  $node = node_load($field['object']->field_place[0]['nid']);
  if(empty($node->location['street'])){
    return;
  }
  $destination = array();
  $fields = array('street', 'city', 'province_name', 'postal_code');
  foreach ($fields as $key) {
    if (!empty($node->location[$key])) {
      $destination[] = check_plain($node->location[$key]);
    }
  }
  if (!empty($destination)) {
    $link ='<a href="http://maps.google.com/?daddr='. urlencode(implode($destination, '+')) .'" target="_blank">'. t('Get Directions') .'</a>';
    return $link;
  }
}

function theme_mt_location_gmap_default($field) {
  $field['format'] = 'nd_location_gmap';
  $field['formatter'] = 'nd_location_gmap_default';
  $node = node_load($field['object']->field_place[0]['nid']);
  if(isset($node->location) && ((!empty($node->location['street']) || !empty($node->location['city']) || !empty($node->location['province']) || !empty($node->location['postal_code'])) || ($node->location['latitude']!='0.000000' && $node->location['longitude']!='0.000000' ) ) ){
    if (!empty($node->location['latitude']) && !empty($node->location['longitude'])) {

      // Defaults.
      $zoom = 'default';
      $width = 'default';
      $height = 'default';
      $latitude = $node->location['latitude'];
      $longitude = $node->location['longitude'];
      if($latitude=='0.000000' && $longitude=='0.000000'){
        $address = $node->location['street'] . ' ' . $node->location['city'] . ' ' . $node->location['province'] . ' ' . $node->location['postal_code'];
        $results = mt_event_feed_google_get_georeference($address);
        $longitude = $results['longitude'];
        $latitude = $results['latitude'];
      }
      $autoclick = FALSE;

      // Check format.
      $format = str_replace('nd_location_gmap_', '', $field['formatter']);
      if ($format != 'default') {
        $formatters = variable_get('nd_location_formatters', array());
        $formatter = $formatters[$format];
        $width = $formatter['width'] .'px';
        $height = $formatter['height'] .'px';
        $zoom = $formatter['zoom'];
        $autoclick = (isset($formatter['autoclick'])) ? $formatter['autoclick'] : FALSE;
      }
      $is_only_state_provided = empty($node->location['street']) && empty($node->location['city']) && empty($node->location['postal_code']) && !empty($node->location['province']);
      if($is_only_state_provided){
        $zoom = '7';
      }
      return theme('nd_location_gmap', $field, $latitude, $longitude, $width, $height, $zoom, $autoclick);
    }
  }
}

function theme_mt_location_textfield($field) {
  if($field['key']=='nd_location_name'){
    $field['key']='name';
  }
  if (!empty($field['object']->location[$field['key']])) {
    $value = $field['object']->location[$field['key']];
    if ($field['key'] == 'country') {
      $value = $field['object']->location['country_name'];
    }
    if ($field['key'] == 'province') {
      $value = $field['object']->location['province_name'];
    }
    if ($field['key'] == 'locpick') {
      // Latitude.
      $value  = '';
      list($degrees, $minutes, $seconds, $negative) = location_dd_to_dms($field['object']->location['latitude']);
      $value .= "${degrees}° ${minutes}' ${seconds}\" ";
      if (!$negative) {
        $value .= 'N';
      }
      else {
        $value .= 'S';
      }
      // Longitude
      list($degrees, $minutes, $seconds, $negative) = location_dd_to_dms($field['object']->location['longitude']);
      $value .= ", ${degrees}° ${minutes}' ${seconds}\" ";
      if (!$negative) {
        $value .= 'E';
      }
      else {
        $value .= 'W';
      }
    }
    return check_plain($value);
  }
}