<?php

include_once('ft_account.features.inc');

/**
 *  Enhancing the user Pages titles and callbacks
 *  https://app.asana.com/0/1044037878840/1212366488866
*/
define("MC_USER_PAGE", t('Sign in'));
define("MC_USER_PAGE_REGISTER", t('Create new account'));
define("MC_USER_PAGE_PASSWORD", t('Request new password'));


//sub function being used at hook_menu_alter
function _mc_user_pages_menu_alter(&$items){
  $user_menus = array(
    'user' => array("title" => MC_USER_PAGE, "weight" => -10),
    'user/login' => array("title" => MC_USER_PAGE, "weight" => -10),
    'user/register' => array("title" => MC_USER_PAGE_REGISTER),
    'user/password' => array("title" => MC_USER_PAGE_PASSWORD)
  );

  $callback = array('page callback' => 'mc_user_page','page arguments' => array(1));

  foreach($user_menus as $path => $menu){
    $items[$path] = array_merge($items[$path],$menu,$callback);
  }
}

function _mc_user_pages_form_alter(&$form, &$form_state, $form_id){
  global $user;

  /*
   * User login form
   */
  if($form_id == "user_login"){

    /*
     * Changing some of the default values on the login fields
     */
    $form['submit']['#value'] = MC_USER_PAGE;
    $form['name']['#description'] = t("Enter your username or email address.");
    $form['pass']['#description'] = t("Enter your password.");
  }

  //move the picture fieldset into Personal information.
  if($form_id=='user_profile_form'){

    /*
     * redirect back to the user profile page
     */
    $form['#redirect'] = "user/".$user->uid;

    /*
      convert picture to a item inside personal information
      'personal information' comes from Profile + ProfileOnePage modules
    */

    if($form['Personal information'] && $form['picture']){
      //move picture to personal information
      $form['Personal information']['picture'] = $form['picture'];

      //remove the original picture fieldset
      unset($form['picture']);

      //convert picture fieldset to an item inside 'Personal Information'
      $form['Personal information']['picture']['#type'] = "item";
      $form['Personal information']['picture']['#weight'] = 100;
      $form['Personal information']['picture']['#title'] = 'Picture';
      $form['Personal information']['picture']['picture_upload']['#title'] = '';

      /**
       * Modify the default User Picture Msg
       * Original msg at /modules/user.module line 1594
       * t('Your virtual face or picture. Maximum dimensions are %dimensions and the maximum size is %size kB.',
       * array('%dimensions' => variable_get('user_picture_dimensions', '85x85'), '%size' => variable_get('user_picture_file_size', '30'))) .' '. variable_get('user_picture_guidelines', ''));
       * */
      $form['Personal information']['picture']['picture_upload']['#description'] = t('Your virtual face or picture. Maximum size is %size kB.', array('%dimensions' => variable_get('user_picture_dimensions', '85x85'), '%size' => variable_get('user_picture_file_size', '30'))) .' '. variable_get('user_picture_guidelines', '');

    }
  }

  //remove the og_register from user registration form.
  if($form_id == "user_register"){
    if($form['account']){
      $form['account']['#type'] = 'item';
      $form['account']['#title'] = "";
      unset($form['account']['mail']['#description']);
    }

    if($form['mail']){
          unset($form['mail']['#description']);
    }

    $form['submit']['#attributes']['class'] = 'btn-orange';
    $form['submit']['#value'] = 'Join';

    //force removing og_registration
    if($form['og_register']){
      unset($form['og_register']);
    }
  }

}

//mc user page logic and callback
function mc_user_page($where){
  module_load_include("inc","user","user.pages");

  switch($where){
    case 'register':
      drupal_set_title(MC_USER_PAGE_REGISTER);
      return drupal_get_form('user_register');
    case 'password':
      drupal_set_title(MC_USER_PAGE_PASSWORD);
      return drupal_get_form('user_pass');
    case 'login':
    default:
      drupal_set_title(MC_USER_PAGE);
      return user_page();
  }  //end switch
}
## End of Enhancing the user Pages titles and Callbacks

function ft_account_menu_alter(&$items){
  _mc_user_pages_menu_alter($items);
}

function ft_account_late_form_alter(&$form, &$form_state, $form_id){
  _mc_user_pages_form_alter($form, $form_state, $form_id);
}

function ft_account_theme($existing, $type, $theme, $path) {
  return array(
    'mc_account_head' => array(
      'arguments' => array(),
      'template' => "mc_account_head"
    )
  );
}

function ft_account_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('My Account section'),
      'weight' => 0,
      'status' => 1,
      'cache' => BLOCK_CACHE_PER_USER
    );
    return $blocks;
  }else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => '',
          'content' => theme('mc_account_head'),
        );
        break;
    }
    return $block;
  }
}