<?php

include_once('ft_account.features.inc');

/**
 *  Enhancing the user Pages titles and callbacks
 *  https://app.asana.com/0/1044037878840/1212366488866
*/
define("MC_USER_PAGE", t('Sign in'));
define("MC_USER_PAGE_REGISTER", t('Create new account'));
define("MC_USER_PAGE_PASSWORD", t('Request new password'));


//sub function being used at hook_menu_alter
function _mc_user_pages_menu_alter(&$items){
  $user_menus = array(
    'user' => array("title" => MC_USER_PAGE, "weight" => -10),
    'user/login' => array("title" => MC_USER_PAGE, "weight" => -10),
    'user/register' => array("title" => MC_USER_PAGE_REGISTER),
    'user/password' => array("title" => MC_USER_PAGE_PASSWORD)
  );

  $callback = array('page callback' => 'mc_user_page','page arguments' => array(1));

  foreach($user_menus as $path => $menu){
    $items[$path] = array_merge($items[$path],$menu,$callback);
  }
}

function _mc_user_pages_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "user_login"){
    $form['submit']['#value'] = MC_USER_PAGE;
  }
}

//mc user page logic and callback
function mc_user_page($where){
  switch($where){
    case 'register':
      drupal_set_title(MC_USER_PAGE_REGISTER);
      return drupal_get_form('user_register');
    case 'password':
      drupal_set_title(MC_USER_PAGE_PASSWORD);
      return drupal_get_form('user_pass');
    case 'login':
    default:
      drupal_set_title(MC_USER_PAGE);
      return user_page();
  }  //end switch
}
## End of Enhancing the user Pages titles and Callbacks

function ft_account_menu_alter(&$items){
  _mc_user_pages_menu_alter($items);
}

function ft_account_form_alter(&$form, &$form_state, $form_id){
  _mc_user_pages_form_alter($form, $form_state, $form_id);
}

function ft_account_theme($existing, $type, $theme, $path) {
  return array(
    'mc_account_head' => array(
      'arguments' => array(),
      'template' => "mc_account_head"
    )
  );
}

function ft_account_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $blocks[0] = array(
      'info' => t('My Account section'),
      'weight' => 0,
      'status' => 1,
      'cache' => BLOCK_CACHE_PER_USER
    );
    return $blocks;
  }else if ($op == 'view') {
    switch ($delta) {
      case 0:
        $block = array(
          'subject' => '',
          'content' => theme('mc_account_head'),
        );
        break;
    }
    return $block;
  }
}