<?php

/**
 * Implementation of hook_perm()
 */
function og_sitewide_perm_perm(){
  $perms = array();
  $perms[] = 'add group content';
  $types = node_get_types();
  foreach($types as $type){
    $t = $type->type;
    $perms[] = "create $t sitewide";
  }
  return $perms;
}

function og_sitewide_perm_late_form_alter(&$form, &$form_state, $form_id){

  //check if it's node form and check it's group post type
  if(!is_ct_form($form,'form') AND !og_is_group_post_type($form['#node']->type)){
      return;
  }

  $node = $form['#node'];

  //Check if has permissions to post sitewide permissions
  $postSitewide = user_access("create " . $node->type . " sitewide");

  if ($postSitewide){
    $none = array(0);
    if(is_array($form['og_nodeapi']['visible']['og_groups']['#options']))
      $ops = &$form['og_nodeapi']['visible']['og_groups']['#options'];
      $ops = array_unshift_assoc($ops,0,"-- None --");
    }
}