<?php

define("MC_OG_MENU_DEFAULT",'og_menu_pages');

function _mc_og_menu_items(){
  return array(
    'home' => array(
      'title' => 'Home',
      'link' => 'node/!nid',
      'show_block' => TRUE
    ),
    'about' => array(
      'title' => 'About',
      'view' => "og_details",
      'display_id' => 'page_1',
      'link' => 'node/!nid/about',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    'latest' => array(
      'title' => 'Latest',
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_1',
      'link' => 'node/!nid/latest',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    'events' => array(
      'title' => "Events",
      'view' => "mc_events_sections",
      'display_id' => 'block_4',
      'link' => 'node/!nid/events',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
      'page_title' => 'Upcoming Events'
    ),
    'articles' => array(
      'title' => "Articles",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_5',
      'link' => 'node/!nid/articles',
      'is_menu_item' => TRUE,
      'show_block' => TRUE
    ),
    'news' => array(
      'title' => "News",
      'view' => "mc_news_sections",
      'display_id' => 'block_1',
      'link' => 'node/!nid/news',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
      'page_title' => 'Recent News'
    ),
    'files' => array(
      'title' => "Files",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_6',
      'link' => 'node/!nid/files',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    /*
    'photos' => array(
      'title' => "Photos",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_7',
      'link' => 'node/!nid/photos',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    */
    'discussions' => array(
      'title' => "Discussions",
      'view' => 'discussions',
      'display_id' => 'page_1',
      'link' => 'node/!nid/discussions',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    'discussions/top' => array(
      'title' => "Discussions",
      'view' => 'discussions',
      'display_id' => 'page_2',
      'link' => 'node/!nid/discussions/top',
      'is_menu_item' => TRUE,
      'show_block' => FALSE,
    ),
    'videos' => array(
      'title' => "Videos",
      'view' => MC_OG_MENU_DEFAULT,
      'display_id' => 'page_8',
      'link' => 'node/!nid/videos',
      'is_menu_item' => TRUE,
      'show_block' => TRUE,
    ),
    'contact' => array(
      'title' => "Contact",
      'link' => 'node/!nid/contact',
      'show_block' => TRUE,
    )
  );
}

/*
 * hook_block
 * @see http://api.drupal.org/api/drupal/developer%21hooks%21core.php/function/hook_block/6
*/
function mc_og_menu_block($op = 'list', $delta = 0, $edit = array()){
  switch($op){
    case 'list':
    $blocks = array();
    $blocks[0] = array(
      'info' => "MC OG Menu",
      'cache' => BLOCK_NO_CACHE,
    );

    return $blocks;
    break;
    case 'view':
      switch ($delta) {
        case 0:
          $block = array(
            'subject' => '',//t('MC OG Menu'),
            'content' => _mc_og_menu_block(),
          );
          break;
        break;
      }

      return $block;
    break;
  }
}

function _mc_og_menu_block(){
  $og = og_get_group_context();
  $links = array();

  if(!empty($og)){
    $nid = $og->nid;
    $og_menu = _mc_og_menu_items();
    $allowed = variable_get('og-menu-allowed',array());

    foreach($og_menu as $key => $og_item){
      if($og_item['show_block']){
        if(empty($allowed) OR (!empty($allowed) && in_array($key,$allowed))){
          $link = &$links[];
          $link['title'] = $og_item['title'];
          $link['href'] = t($og_item['link'],array('!nid' => $nid));
        }
      }
    }

    return theme('links',$links,array('class' => 'menu mc-og-menu'));
  }

  return '';
}

/**
 * hook_menu
 * @return array
 * @see http://api.drupal.org/api/drupal/developer%21hooks%21core.php/function/hook_menu/6
 */
function mc_og_menu_menu(){
  $items = array();
  $menu_list = _mc_og_menu_items();
  foreach($menu_list as $key => $item){
    if($item['is_menu_item']){
      $view = $item['view'];
      $display = $item['display_id'];
      $path = t($item['link'],array('!nid' => '%node'));
      $items[$path] = array(
        'title' => $item['title'],
        'page callback' => '_mc_load_view_page',
        'page arguments' => array(1,$item),
        'access arguments' => array('access content'),
        'type' => MENU_CALLBACK,
      );
    }
  }

  return $items;
}

/**
 * mc_og_menu page callback
 * @param $node current og node
 * @param $item menu item from _mc_og_menu_items()
 * @return bool|void
 */
function _mc_load_view_page($node,$item){
  $view = $item['view'];
  $display = $item['display_id'];

  if(!empty($item['page_title'])){
    drupal_set_title($item['page_title']);
  }

  if(og_is_group_type($node->type)){
    return views_embed_view($view,$display);
  }

  return drupal_not_found();
}