<?php

define('DUMMYIMAGE_GENERATE_NONE', 1);
define('DUMMYIMAGE_GENERATE_MISSING', 2);
define('DUMMYIMAGE_GENERATE_ALL', 3);

/**
 * Implementation of hook_menu().
 */
function dummyimage_menu() {
  $items = array();

  $items['admin/build/imagecache/dummyimage'] = array(
    'title' => 'Dummy images',
    'description' => 'Use dummy image services for image content.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dummyimage_admin_form'),
    'access arguments' => array('administer dummyimage'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implementation of hook_perm()
 */
function dummyimage_perm() {
  return array( 'administer dummyimage');
}

/**
 * Admin settings form.
 */
function dummyimage_admin_form() {
  $options = array(
    DUMMYIMAGE_GENERATE_NONE => t('For no images'),
    DUMMYIMAGE_GENERATE_MISSING => t('For missing images'),
    DUMMYIMAGE_GENERATE_ALL => t('For all images'),
  );
  $form['dummyimages_generate'] = array(
    '#type' => 'radios',
    '#title' => t('Use dummy images'),
    '#options' => $options,
    '#default_value' => variable_get('dummyimages_generate', DUMMYIMAGE_GENERATE_NONE),
  );
  $form['dummyimage_default_dimensions'] = array(
    '#type' => 'textfield',
    '#title' => t('Default dimensions'),
    '#description' => t('Enter a dimension (preset size) in the format [width]x[height]. If the dummyimage module cannot determine a dimension to use, it will fall back to this dimension. Defaults to 300x300.'),
    '#size' => 12,
    '#default_value' => variable_get('dummyimage_default_dimensions', '300x300'),
  );

  $services[] = l('Dummy image', 'http://dummyimage.com');
  $services[] = l('Placekitten', 'http://placekitten.com');
  $services[] = l('Lorem Pixum', 'http://lorempixum.com');
  $services[] = l('Flickholdr', 'http://flickholdr.com');

  $form['dummyimages_service'] = array(
     '#type' => 'select',
     '#title' => t('Service'),
     '#description' => t('Select the service you would like to use for your dummy images. You can currently choose between these services: !services', array('!services' => theme('item_list', $services))),
     '#default_value' => variable_get('dummyimages_service', 'dummyimage'),
     '#options' => array(
       'dummyimage' => t('Dummy Image'),
       'placekitten' => t('Placekitten'),
       'lorempixum' => t('Lorem Pixum'),
       'flickholdr' => t('Flickholdr'),
       ),
   );

   $form['dummyimage'] = array(
      '#type' => 'fieldset',
      '#title' => t('Dummy Image'),
      '#tree' => FALSE,
      '#collapsible' => TRUE,
      '#collapsed' => TRUE,
      '#prefix' => '<h3>' . t('Configuration') . '</h3>',
    );
   $form['dummyimage']['dummyimage_color'] = array(
     '#type' => 'textfield',
     '#title' => t('Color'),
     '#description' => t('Enter the hex code of the color you want for the foreground. Do not include the #. Defaults to 000000.'),
     '#size' => 12,
     '#maxlength' => 255,
     '#default_value' => variable_get('dummyimage_color', '000000'),
   );
   $form['dummyimage']['dummyimage_background'] = array(
     '#type' => 'textfield',
     '#title' => t('Background color'),
     '#description' => t('Enter the hex code of the color you want for the background. Do not include the #. Defaults to CCCCCC.'),
     '#size' => 12,
     '#maxlength' => 255,
     '#default_value' => variable_get('dummyimage_background', 'CCCCCC'),
   );
  $form['kittehs'] = array(
     '#type' => 'fieldset',
     '#title' => t('Kittehs'),
     '#tree' => FALSE,
     '#collapsible' => TRUE,
     '#collapsed' => TRUE,
   );
   $form['kittehs']['dummyimage_kittens_color'] = array(
      '#type' => 'checkbox',
      '#title' => t('I can haz kittehs wif color?'),
      '#description' => t('Will use color fotos ov kittehs. Otherwize black an white will bees usd'),
      '#default_value' => variable_get('dummyimage_kittens_color', 0),
    );

    $form['lorempixum'] = array(
       '#type' => 'fieldset',
       '#title' => t('Lorem Pixum'),
       '#tree' => FALSE,
       '#collapsible' => TRUE,
       '#collapsed' => TRUE,
     );

    $form['lorempixum']['dummyimage_lorempixum_color'] = array(
      '#type' => 'checkbox',
      '#title' => t('Color Images?'),
      '#default_value' => variable_get('dummyimage_lorempixum_color', 0),
    );

    $form['lorempixum']['dummyimages_lorempixum_category'] = array(
      '#type' => 'select',
      '#title' => t('Category'),
      '#options' => array(
        'random' => t('Random'),
        'abstract' => t('Abstract'),
        'food' => t('Food'),
        'people' => t('People'),
        'technics' => t('Technics'),
        'animals' => t('Animals'),
        'nightlife' => t('Nightlife'),
        'nature' => t('Nature'),
        'transport' => t('Transport'),
        'city' => t('City'),
        'fashion' => t('Fashion'),
        'sports' => t('Sports'),
      ),
      '#default_value' => variable_get('dummyimages_lorempixum_category', 'random'),
    );

    $form['flickholdr'] = array(
       '#type' => 'fieldset',
       '#title' => t('Flickholdr'),
       '#tree' => FALSE,
       '#collapsible' => TRUE,
       '#collapsed' => TRUE,
     );
     $form['flickholdr']['dummyimage_flickholdr_tags'] = array(
       '#type' => 'textfield',
       '#title' => t('Flickr tags'),
       '#description' => t('Enter one or more tags. If you use more than one, separate them with commas.'),
       '#size' => 40,
       '#maxlength' => 255,
       '#default_value' => variable_get('dummyimage_flickholdr_tags', 'tapir'),
     );
    $form['flickholdr']['dummyimage_flickholdr_color'] = array(
      '#type' => 'checkbox',
      '#title' => t('Color Images?'),
      '#default_value' => variable_get('dummyimage_flickholdr_color', 1),
    );
  return system_settings_form($form);
}

/**
 * Implementation of hook_theme_registry_alter().
 */
function dummyimage_theme_registry_alter(&$theme_registry) {
  if (DUMMYIMAGE_GENERATE_NONE != variable_get('dummyimages_generate', DUMMYIMAGE_GENERATE_NONE)) {
    $theme_registry['imagecache']['function'] = 'dummyimage_imagecache';
    $theme_registry['imagecache']['theme paths'][] = drupal_get_path('module', 'dummyimage');
  }
  elseif ('dummyimage_imagecache' == $theme_registry['imagecache']['function']) {
    $theme_registry['imagecache']['function'] = 'theme_imagecache';
    foreach ($theme_registry['imagecache']['theme paths'] as $key => $value) {
      if (drupal_get_path('module', 'dummyimage') == $value) {
        unset($theme_registry['imagecache']['theme paths'][$key]);
      }
    }
  }
}

/**
 * Gets the best-effort size for the imagecache preset.
 *
 * @return
 *  string the preset size in the format [width]x[height]
 */
function _dummyimage_get_preset_url($presetname) {
  static $sizes = array();
  static $dummy_urls = array();
  if (!isset($dummy_urls[$presetname])) {
    $preset = imagecache_preset_by_name($presetname);
    $actions = isset($preset['actions']) ? $preset['actions'] : imagecache_preset_actions($preset);
    $width = '';
    $height = '';
    if (isset($actions)) {
      foreach ($actions as $action) {
        if (!empty($action['data']['width'])) {
          $width = $action['data']['width'];
        }
        if (!empty($action['data']['height'])) {
          $height = $action['data']['height'];
        }
      }
    }
    $size = 0;
    if (empty($width) && empty($height)) {
      $size = variable_get('dummyimage_default_dimensions', '300x300');
    }
    else if (variable_get('dummyimages_service', 'dummyimage') && (empty($width) || empty($height))) {
      $size = empty($width) ? $height . 'x' . $height : $width . 'x' . $width;
    }
    else {
      // Height is optional for dummyimage.com, so make sure we never have
      // [empty]x[height].
      $size = empty($width) ? $height : $width . 'x' . $height;
    }
    switch (variable_get('dummyimages_service', 'dummyimage')) {
      case 'dummyimage':
        $color =  variable_get('dummyimage_color', '000000');
        $background =  variable_get('dummyimage_background', 'cccccc');
        $dummy_urls[$presetname] = "http://dummyimage.com/{$size}/$background/$color.png";
        break;
      case 'placekitten':
        $color = (variable_get('dummyimage_kittens_color', 0) == 1) ? '' : 'g/';
        $size = strtr($size, 'x', '/');
        $dummy_urls[$presetname] = "http://placekitten.com/$color$size";
        break;
      case 'lorempixum':
        $color = (variable_get('dummyimage_lorempixum_color', 0) == 1) ? '' : 'g/';
        $size = strtr($size, 'x', '/');
        $category = (variable_get('dummyimages_lorempixum_category', 'random') == 'random') ? '' : variable_get('dummyimages_lorempixum_category', 'random');
        $dummy_urls[$presetname] = "http://lorempixum.com/$color$size/$category";
        break;
      case 'flickholdr':
        $color = (variable_get('dummyimage_flickholdr_color', 1) == 0) ? '/bw' : '';
        $size = strtr($size, 'x', '/');
        $tags = str_replace(' ', '', variable_get('dummyimage_flickholdr_tags', 'tapir'));
        $dummy_urls[$presetname] = "http://flickholdr.com/$size/$tags$color";
        break;
    }
  }
  return $dummy_urls[$presetname];
}

function _dummyimage_get_random_image() {
  switch (variable_get('dummyimages_service', 'dummyimage')) {
    case 'placekitten':
      return '?image=' . rand(1, 16);
      break;
    case 'lorempixum':
      if ('random' == variable_get('dummyimages_lorempixum_category', 'random')) {
        return '';
      }
      return '/' . rand(1, 10);
      break;
    case 'flickholdr':
      return '/' . rand(1, 10);
      break;
  }
  return '';
}

function dummyimage_imagecache($presetname, $path, $alt = '', $title = '', $attributes = NULL, $getsize = TRUE) {
  switch (variable_get('dummyimages_generate', DUMMYIMAGE_GENERATE_NONE)) {
    case DUMMYIMAGE_GENERATE_MISSING:
      if (is_file($path)) {
        break;
      }
    case DUMMYIMAGE_GENERATE_ALL:
      // Check is_null() so people can intentionally pass an empty array of
      // to override the defaults completely.
      if (is_null($attributes)) {
        $attributes = array('class' => 'imagecache imagecache-'. $presetname);
      }
      $attributes = drupal_attributes($attributes);
      $dummy_url = _dummyimage_get_preset_url($presetname) . _dummyimage_get_random_image();
      return '<img src="'. $dummy_url .'" alt="'. check_plain($alt) .'" title="'. check_plain($title) .'" '. $attributes .' />';
      break;
  }
  return theme_imagecache($presetname, $path, $alt, $title, $attributes, $getsize);
}
