<?php
/**
 * @file
 * Code for the Feature Landing Contexts feature.
 */

include_once 'ft_landing_contexts.features.inc';


function ft_landing_contexts_theme_registry_alter(&$theme_registry) {
  $modulepath = drupal_get_path('module', 'ft_landing_contexts');
  
  // Alter block theme paths
  $originalpath = array_shift($theme_registry['block']['theme paths']);
  array_unshift($theme_registry['block']['theme paths'], $originalpath, $modulepath);
}

/**
 * used at landing page contexts to find out what is the current landing page name/type
 * @param string $type
 * @return bool
 */
function _is_landingpage($type = 'homepage'){
  $node = menu_get_object();

  if($node){
    if($node->type == "npage"){
      $node_type = $node->field_page_type[0]['value'];
      $node_subtype = $node->field_page_subtype[0]['value'];
      if($node_type == "landing" && $node_subtype == $type){
        return TRUE;
      }
    }
  }

  return FALSE;
}

function ft_landing_contexts_context_load_alter(&$context){

  if($context->name == "sitewide" && variable_get("hide-search-bar",false)){
    unset($context->reactions['block']['blocks']['search-0']);
  }

  if(variable_get("hide-og-menu",false) && isset($context->reactions['block']['blocks']['mc_og_menu-0'])){
    unset($context->reactions['block']['blocks']['mc_og_menu-0']);
  }
}