<?php

function mc_taxonomynode_form_alter(&$form, &$form_state, $form_id) {
	if($form_id=='taxonomy_form_vocabulary'){
		if(isset($form['taxonomynode']['taxonomynode_content_type']) && is_array($form['taxonomynode']['taxonomynode_content_type'])){
			$machine_name = $form['module']['#value'];
			$mc_variable = variable_get('mc_taxonomynode_' . $machine_name , '');
			if($mc_variable!=''){
				$form['taxonomynode']['taxonomynode_content_type']['#default_value'] = $mc_variable;
			}
		}
	}
}


function mc_taxonomynode_taxonomy($op, $type, $array = NULL) {
  if ($type == 'vocabulary' && isset($array['taxonomynode_content_type'])) {
    $vid = $array['vid'];
    $machine_name = $array['module'];
    $content_type = $array['taxonomynode_content_type'];
    if ($op == 'insert' || $op == 'update') {
      $taxonomynode_settings['content_type'] = $content_type;
      variable_set('mc_taxonomynode_' . $machine_name, $taxonomynode_settings);
    }

    if ($op == 'delete') {
      variable_del('mc_taxonomynode_' . $machine_name);
    }
  }
}


function mc_taxonomynode_init(){
	$has_run = variable_get('mc_taxonomynode_run', false);
	if(!$has_run){
		$results = db_query("SELECT vid FROM {vocabulary}");
  	while($row = db_fetch_array($results)){
	    $vid = $row['vid'];
	    $vocabulary = taxonomy_vocabulary_load($vid);
	    $machine_name = $vocabulary->module;
	    $mc_value = variable_get('mc_taxonomynode_' . $machine_name , '');
	    $taxonomynode_value = variable_get("taxonomynode_{$vid}", '');
	    if(($taxonomynode_value=='' || $taxonomynode_value!=$mc_value ) && $mc_value!=''){
	    	variable_set("taxonomynode_{$vid}", $mc_value);
	    }
  	}
  	variable_set('mc_taxonomynode_run', true);
	}
}