<?php
//
/**
* Implementation of hook_views_api().
*/
function event_views_views_api()
{
   return array(
   'api' => 2,
   );
}

function event_views_init()
{
   //Quick hack to fix old installs.  This will eventually be taken out.
   if (!event_views_check_schema())
   {
      drupal_set_message("Note:  Event Views detected that you were very likely running the old version of event_views and has updated your DB tables with new fields required to use the new event_views module.");
   }
}

//This checks to see if fields we need actually exist.  If they dont, then re-run the install script.
function event_views_check_schema()
{
   if (db_column_exists('event', 'unix_event_start') && db_column_exists('event', 'unix_event_end'))
   {
      return TRUE;
   }

   require_once(drupal_get_path('module', 'event_views').'/event_views.install');
   event_views_install();
   return FALSE;
}

function event_views_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL)
{
   //Update the timestamp fields in the event table
   if ($op == 'update' || $op == 'insert')
   {
      if ($node->event['start_exploded']['month'])
      {
         $start_hour = $node->event['start_exploded']['hour'];// + $node->event['start_in_dst'];
         $timezone = event_zonelist_by_id($node->event['timezone']);
           if($timezone['offset_dst']=='00:00:00'){
            $timezone['offset_dst'] = "+" . $timezone['offset_dst'];
         }
         if(!$node->event['start_in_dst']){
           $timezone_offset_start = $timezone['offset'];
         }
         else {
           $timezone_offset_start = $timezone['offset_dst'];
         }
         $date = $node->event['start_exploded']['year'].'-'.
         $node->event['start_exploded']['month'].'-'.
         $node->event['start_exploded']['day'].' '.
         $start_hour.':'.
         $node->event['start_exploded']['minute'].':00 ' .
         preg_replace('/00$/', '',str_replace(':', '', $timezone_offset_start));
         $date = preg_replace('/ \d{4}$/', '', $date);
         $timestamp = strtotime($date);
         $query = "UPDATE {event} SET unix_event_start = '%d' WHERE nid = '%d'";
         db_query($query, $timestamp, $node->nid);

         if(!$node->event['end_in_dst']){
           $timezone_offset_end = $timezone['offset'];
         }
         else {
           $timezone_offset_end = $timezone['offset_dst'];
         }
         $end_hour = $node->event['end_exploded']['hour'];// + $node->event['end_in_dst'];
         $date = $node->event['end_exploded']['year'].'-'.
         $node->event['end_exploded']['month'].'-'.
         $node->event['end_exploded']['day'].' '.
         $end_hour.':'.
         $node->event['end_exploded']['minute'].':00'.
         preg_replace('/00$/', '',str_replace(':', '', $timezone_offset_end));
         $date = preg_replace('/ \d{4}$/', '', $date);
         $timestamp = strtotime($date);
         $query = "UPDATE {event} SET unix_event_end = '%d' WHERE nid = '%d'";
         db_query($query, $timestamp, $node->nid);
      }
   }
}